version: '2'

services:

### Applications Code Container #############################

    applications:
        container_name: docker_app
        image: tianon/true
        volumes:
            - ../:/var/www
#            - ~/jmt-backend:/var/www/jmt-backend
#            - ~/backend-ui:/var/www/backend-ui
#            - ~/message-management:/var/www/message-management
#            - ../sample/:/var/www/sample

### Workspace Utilities Container ###########################

    workspace:
        container_name: docker_workspace
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_SOAP=false
                - INSTALL_MONGO=false
                - INSTALL_NODE=true
                - INSTALL_YARN=false
                - INSTALL_DRUSH=false
                - INSTALL_AEROSPIKE_EXTENSION=false
                - COMPOSER_GLOBAL_INSTALL=false
                - INSTALL_WORKSPACE_SSH=false
                - INSTALL_LARAVEL_ENVOY=false
                - INSTALL_DEPLOYER=false
                - INSTALL_LINUXBREW=false
                - PUID=1000
                - PGID=1000
                - NODE_VERSION=stable
                - RUN_SUPERVISOR=false
                - TZ=Asia/Bangkok
        volumes_from:
            - applications
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:192.168.88.247"
        ports:
           - "2222:22"
        stdin_open: true
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        container_name: docker_fpm
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_MONGO=false
                - INSTALL_ZIP_ARCHIVE=true
                - INSTALL_PHPREDIS=false
                - INSTALL_MEMCACHED=true
                - INSTALL_OPCACHE=false
                - INSTALL_EXIF=false
                - INSTALL_AEROSPIKE_EXTENSION=false
                - CODEIGNITER=false
                - PUID=1001
            dockerfile: Dockerfile-70
        volumes_from:
            - applications
        expose:
            - "9000"
            - "8888"
        links:
            - workspace
            - postgres
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:192.168.88.247"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG=serverName=laravel


### Nginx Server Container ##################################

    nginx:
        container_name: docker_nginx
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - applications
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm
            - django

        stdin_open: true
        tty: true

### Apache Server Container #################################

#    apache2:
#        build:
#            context: ./apache2
#            args:
#                - PHP_SOCKET=php-fpm:9000
#        volumes_from:
#            - applications
#        volumes:
#            - ./logs/apache2:/var/log/apache2
#        ports:
#            - "80:80"
#            - "443:443"
#        links:
#            - php-fpm

### HHVM Container ##########################################

#    hhvm:
#        build: ./hhvm
#        volumes_from:
#            - applications
#        expose:
#            - "9000"
#        links:
#            - workspace

### MySQL Container #########################################

#    mysql:
#        container_name: docker_mysql
#        build: ./mysql
            #        volumes:
#            - docker_mysql:/var/lib/mysql
            #        ports:
#            - "3306:3306"
#        environment:
                # MYSQL_DATABASE:homestead
                # MYSQL_USER:homestead
                # MYSQL_PASSWORD:secret
                # MYSQL_ROOT_PASSWORD: aabbccddee

### MariaDB Container #######################################

    mariadb:
        container_name: docker_mariadb
        build: ./mariadb
        volumes:
            - docker_mariadb:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: aabbccddee

### PostgreSQL Container ####################################

    postgres:
        container_name: docker_postgres
        build: ./postgres
        volumes:
            - docker_postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: homestead
            POSTGRES_USER: homestead
            POSTGRES_PASSWORD: secret

### PostgreSQL PostGis Container ############################

#    postgres-postgis:
#        build: ./postgres-postgis
#        volumes:
#            - postgres:/var/lib/postgresql/data
#        ports:
#            - "5432:5432"
#        environment:
#            POSTGRES_DB: homestead
#            POSTGRES_USER: homestead
#            POSTGRES_PASSWORD: secret

### Neo4j Container #########################################

#    neo4j:
#        build: ./neo4j
#        ports:
#            - "7474:7474"
#            - "1337:1337"
#        environment:
#            - NEO4J_AUTH=homestead:secret
#        volumes:
#            - neo4j:/var/lib/neo4j/data

### MongoDB Container #######################################

    #mongo:
    #     container_name: docker_mongo
    #    build: ./mongo
    #    ports:
    #        - "27017:27017"
    #    volumes:
    #        - docker_mongo:/data/db


### Redis Container #########################################

    redis:
        container_name: docker_redis
        build: ./redis
        volumes:
            - docker_redis:/data
        ports:
            - "6379:6379"

### Aerospike c Container ###################################

#    aerospike:
#        build: ./aerospike
#        volumes_from:
#            - workspace
#        volumes:
#            - aerospike:/opt/aerospike/data
#        ports:
#            - "3000:3000"
#            - "3001:3001"
#            - "3002:3002"
#            - "3003:3003"


### Memcached Container #####################################

    memcached:
        container_name: docker_memcached
        build: ./memcached
        volumes:
            - docker_memcached:/var/lib/memcached
        ports:
            - "11211:11211"
        links:
            - php-fpm

### Beanstalkd Container ####################################

#    beanstalkd:
#        build: ./beanstalkd
#        ports:
#            - "11300:11300"
#        privileged: true
#        links:
#            - php-fpm

### RabbitMQ Container ######################################

#    rabbitmq:
#        build: ./rabbitmq
#        ports:
#            - "5672:5672"
#            - "15671:15671"
#            - "8080:15672"
#        privileged: true
#        environment:
#            RABBITMQ_DEFAULT_USER: guest
#            RABBITMQ_DEFAULT_PASS: guest
#        links:
#            - php-fpm

### Beanstalkd Console Container ############################

#    beanstalkd-console:
#        build: ./beanstalkd-console
#        ports:
#            - "2080:2080"
#        links:
#            - beanstalkd

### Caddy Server Container ##################################

#    caddy:
#        build: ./caddy
#        ports:
#            - "80:80"
#            - "443:443"
#            - "2015:2015"
#        volumes_from:
#            - applications
#        volumes:
#            - ./caddy/Caddyfile:/etc/Caddyfile
#            - ./logs/caddy:/var/log/caddy
#            - caddy:/root/.caddy
#        links:
#            - php-fpm

### phpMyAdmin Container ####################################

    phpmyadmin:
        container_name: docker_pma
        build: ./phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - docker_phpmyadmin:/sessions
        ports:
            - "8080:80"
        links:
            # for mysql container
#            - "mysql:db"
            # for mariadb container
             - "mariadb:db"

### pgAdmin Container #######################################

    pgadmin:
        container_name: docker_pgadmin
        build: ./pgadmin
        ports:
            - "5050:5050"
        links:
            - postgres

### ElasticSearch Container #################################

    elasticsearch:
        container_name: docker_elasticsearch
        build: ./elasticsearch
        volumes:
            - docker_elasticsearch_data:/usr/share/elasticsearch/data
            - docker_elasticsearch_plugins:/usr/share/elasticsearch/plugins
        ports:
            - "9200:9200"
            - "9300:9300"
        links:
            - php-fpm

### Kibana Container #################################
    kibana:
        container_name: docker_kibana
        image: kibana:latest
        ports:
          - "5601:5601"
        links:
          - elasticsearch

### Logstash Container #################################
    # logstash:
    #     container_name: docker_logstash
    #     image: logstash:2
    #     links:
    #       - elasticsearch

### Django Container #################################
    django:
        container_name: docker_django
        build: ./django
        command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
        volumes:
            - ~/ai-service:/opt/src
        env_file: .env
        environment:
            DEBUG: 'true'
        ports:
            - "8000:8000"
        links:
            - postgres:postgres
            - redis:redis

### Oracle Container #################################
#     oracle:
#         container_name: docker_oracle
#         image: wnameless/oracle-xe-11g
# #        volumes:
# #          - docker_oracle:/
#         environment:
#             ORACLE_ALLOW_REMOTE: 1
#         ports:
#           - "49160:22"
#           - "1521:1521"

### Volumes Setup ###########################################

volumes:
    docker_oracle:
        driver: "local"
    docker_mysql:
        driver: "local"
    docker_postgres:
        driver: "local"
    docker_memcached:
        driver: "local"
    docker_redis:
        driver: "local"
    docker_neo4j:
        driver: "local"
    docker_mariadb:
        driver: "local"
    docker_mongo:
        driver: "local"
    docker_phpmyadmin:
        driver: "local"
    docker_aerospike:
        driver: "local"
    docker_caddy:
        driver: "local"
    docker_elasticsearch_data:
        driver: "local"
    docker_elasticsearch_plugins:
        driver: "local"
    docker_sessions:    ## nothing is connected to this (- ./data/sessions:/sessions)
        driver: "local"
