FROM postgres:latest

MAINTAINER Ben M <git@bmagg.com>

CMD ["postgres"]

#RUN createdb -h localhost -p 5432 -U homestead play2pay
#RUN createdb -h localhost -p 5432 -U homestead jmt
#RUN createdb -h localhost -p 5432 -U homestead line

EXPOSE 5432